### ISSUE TITLE
add sound while sorting/shuffling

### ISSUE THREAD

**Issue by DontBlameMe99** [dormant-chicken/sortty#5]
It would be really amazing if the program would have the "iconic" sound while sorting (maybe even toggleable via an argument)?

Thanks for the awesome program!

**Comment by dormant-chicken** [comment]
Sorry for the late reply, I added a simple sine wave sound to the program with an argument to turn it on or off.

Here is a test program for you to try out before I add it to the main branch.

[sortty.txt](https://github.com/user-attachments/files/16336910/sortty.txt)

It's in a .txt format because github won't let me attach files with .py or without a file extension

To download it, right click and `save link as`

Before running it, install the `portaudio` package for your system and install pysine, which is what allows the program to play the sound

```
pip install pysine
```

To run it, type

```
python3 sortty.txt --sound
```

The `--sound` argument toggles sound

Let me know what you think.

**Comment by DontBlameMe99** [comment]
Thats pretty amazing. There are two things "missing" in my opinion:
1. Sound volume customization. Currently it is really loud for me and I'd wish to customize the volume by e.g. using `--sound-volume 50` for 50% or something like that
2. Customizing the pitch. At the moment the pitch is a little bit lower than compared to those videos. It would be amazing to be able to customize the pitch by e.g. using` --sound-pitch 1.5` for 1.5 times the "height"

All in all it is pretty amazing and I am so thankful for you working on that. I already watched this on -a forever way too long :joy:

**Comment by dormant-chicken** [comment]
I could only add changing the pitch, which will be added to the main branch, but not the volume. I used pysine to generate the sound, because it was the most simple solution, but because of how limited it is, the volume could not be changed.

This issue will be closed

Thanks for contributing :)
